language: python
python:
    - 3.8.2

matrix:
    include:
        - python:3.8.2
install:
    - pip install requests

script:
    - python APOD_Implement.py
    - python Photo.py
    - python DB_Abs.py
    - python APOD_Abs.py
    - python APIReq_Test.py	